In [1]:
import pandas as pd
import os
import random
import sys
import numpy as np

In [2]:
sys.path.append(os.path.join(os.path.dirname(os.getcwd()),"dnasurvey"))
import StartPage, QuestionPage, ThankYouPage, DNASurvey

In [3]:
os.path.dirname(os.getcwd())

'/home/madan/code/dna_survey'

In [4]:
df = pd.read_excel("/home/madan/code/dna_survey/Responses/Jimmy_Survey_89shf9_responses.xlsx")


In [5]:
print(df.index[df["Response"] == "<missing>"][0])

8


In [ ]:
a = list(range(90))
random.shuffle(a)


[27, 25, 88, 16, 85]


In [13]:
print(a[:5])

[27, 25, 88, 16, 85]


In [7]:
b = df.index[df["Response"]=='<missing>']


In [16]:
np.intersect1d(a,b, return_indices=True)

(array([ 8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24,
        25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
        42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58,
        59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75,
        76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89]),
 array([41, 25, 20, 34, 74, 83, 40, 48,  3, 80, 44, 32, 54, 68,  9, 21, 15,
         1,  7,  0, 47, 11, 43, 30, 77, 52, 31, 82, 28, 50, 72, 38, 88, 22,
        29, 79, 55, 84, 37, 58, 66, 33, 13, 63, 36, 46, 14, 89, 86,  6, 81,
        76, 61, 24, 49, 39, 10, 71, 23,  5, 64, 35, 85, 73, 67, 12, 57, 56,
        59, 16, 18, 78, 75,  8, 51, 42, 70,  4, 19, 27,  2, 26]),
 array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
        34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
        51, 52, 53, 54, 55, 56, 